version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    tty: true
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuuhaku-bot
    working_dir: /usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    tty: true
    restart: unless-stopped
volumes:
  redis_data: